version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    depends_on:
      - redis
    image: dockerfacile/app
    ports:
      - "5000:5000"
    environment:
      - starwars=1